# -*- coding: utf-8 -*-
"""Test DM-GCN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134F5mplNblAZhYLu06emr0GRXTbCGn0-
"""

!git clone https://github.com/pangsg/DM-GCN.git

import os; os.chdir("/content/DM-GCN")

!python train.py --dataset "Tweets"

!python prepare_vocab.py --dataset "Tweets"

!python eval.py --save_dir "./saved_models/best_model.pt" --dataset "Tweets"

